import type { ShotFocus } from "@/components/product-shot";

/*
 * Real product assets, in one place.
 *
 * The client's strongest objection to the first design round was that the site
 * showed hand-built HTML approximations of Flavor Studio instead of the product
 * itself — and that the simplified label markup did not follow the official
 * formatting rules those panels are held to.
 *
 * Every entry below with a `src` is exported straight from the Flavor Studio
 * application design file (Figma "Flavor Studio Application"), including the
 * Nutrition Facts panel, which is the label engine's own output rather than a
 * redraw in HTML.
 *
 * Two things were done to the exports after a fit review:
 *
 * - They are CROPPED. A 1440px application window shrunk into a half-width
 *   column turns the interface into texture, and most exports carried a large
 *   empty canvas under the cards. Each file is now cut to the region the copy
 *   is about, with the application chrome kept where it helps orientation.
 * - Each carries a FOCUS region — the part of the frame the copy beside it
 *   discusses — which ProductShot spotlights once the frame scrolls into view.
 *
 * Two exports were retouched, and only in these ways: real names and e-mail
 * addresses in the taste-test export were replaced with placeholders (the
 * client's own spec says "no personal data"), and a one-letter typo in the AI
 * comparison caption ("Recipe A is … Recipe A is") became "Recipe B is".
 *
 * Modules with no design coverage yet keep a `spec` and no `src`, so AssetFrame
 * renders a marked placeholder. Drop the file into /public, add `src`, `width`
 * and `height`, and the placeholder becomes the real thing.
 */

export type AssetSpec = {
  /** Path under /public. Absent = still outstanding, renders as a placeholder. */
  src?: string;
  /**
   * The region of the screenshot the surrounding copy is about, in % of the
   * image. When present, the frame spotlights it once it scrolls into view —
   * see ProductShot. Omit for images that are the point in their entirety.
   */
  focus?: ShotFocus;
  /** What the asset shows. Doubles as the alt text. */
  alt: string;
  /** What we still need from the client, stated concretely. Placeholders only. */
  spec: string;
  width: number;
  height: number;
  kind?: "screenshot" | "label";
};

const SHOT =
  "PNG or JPG, at least 1600px wide, light UI theme, no personal data.";

export const productAssets = {
  /* -------------------------------------------------------------- recipes */
  recipeGrid: {
    src: "/product/recipe-view.png",
    alt: "The Recipe page — formulation grid with the live Yield / Cost sidebar",
    focus: { x: 72, y: 22.7, w: 23, h: 77, label: "Yield / Cost sidebar" },
    spec: "",
    width: 1440,
    height: 606,
  },
  recipeCost: {
    /* The grid and sidebar without the page header, for the narrower slots. */
    src: "/product/recipe-grid.png",
    alt: "The formulation grid beside the Yield / Cost sidebar, with batch cost, container cost and retail price",
    focus: { x: 73.1, y: 28.6, w: 24.7, h: 15.2, label: "Live cost roll-up" },
    spec: "",
    width: 1339,
    height: 498,
  },
  recipeVersions: {
    src: "/product/recipe-versions.png",
    alt: "Recipe versions — V1, Testing and Final switched from the recipe header",
    focus: { x: 1.5, y: 6, w: 21, h: 13, label: "Named versions" },
    spec: "",
    width: 963,
    height: 392,
  },
  ingredientLibrary: {
    src: "/product/new-ingredient.png",
    alt: "New Ingredient — basic information, with a separate Canadian label and French ingredient statement",
    focus: {
      x: 41.4,
      y: 40,
      w: 53.1,
      h: 22,
      label: "Canadian label & French statement",
    },
    spec: "",
    width: 840,
    height: 900,
  },
  ingredientNutrients: {
    src: "/product/ingredient-nutrients.png",
    alt: "New Ingredient — nutrients imported from a supplier PDF, with the allergens section beneath",
    focus: {
      x: 40.6,
      y: 10.4,
      w: 54,
      h: 3.8,
      label: "Import from a supplier PDF",
    },
    spec: "",
    width: 840,
    height: 1075,
  },

  /* ------------------------------------------------------------- labeling */
  nutritionLabelUs: {
    src: "/labels/nutrition-facts-fda.png",
    alt: "FDA Nutrition Facts panel generated by Flavor Studio",
    spec: "",
    width: 688,
    height: 750,
    kind: "label" as const,
  },
  nutritionLabelFormats: {
    /* The layout picker beside the panel it generates. The full dialog is
       `publishExport`. */
    src: "/product/label-layouts.png",
    alt: "Label layouts — vertical, tabular, side-by-side, linear, dual column and aggregate — beside the generated panel",
    focus: { x: 2, y: 2, w: 22, h: 41, label: "Six layouts" },
    spec: "",
    width: 677,
    height: 535,
    kind: "label" as const,
  },
  nutrientClaims: {
    src: "/product/nutrient-content-claims.png",
    alt: "Nutrient Content Claims — the actual value beside each claim's threshold",
    focus: { x: 32, y: 24.7, w: 66.7, h: 52.7, label: "Actual vs threshold" },
    spec: "",
    width: 1360,
    height: 339,
  },
  labelDesigner: {
    src: "/product/publish-designer.png",
    alt: "Publish Designer — template list, element palette, the canvas and the design inspector",
    focus: { x: 1, y: 36.3, w: 15, h: 63.7, label: "Element palette" },
    spec: "",
    width: 1440,
    height: 520,
  },

  /* --------------------------------------------------------------- costing */
  costAssumptions: {
    src: "/product/cost-assumptions.png",
    alt: "The Cost panel — packaging, tolling and freight assumptions rolling up to cost delivered, margin and retail price",
    focus: {
      x: 4,
      y: 28.1,
      w: 91.6,
      h: 42.9,
      label: "Assumptions by category",
    },
    spec: "",
    width: 346,
    height: 922,
  },

  /* ------------------------------------------------------------- projects */
  projectGantt: {
    /* The Timeline view of a project's Work tab, from the Figma section "04
       Pillars — synced to dev" (40000493:89173), cropped to the title, the
       tabs and the Gantt; the task detail panel below it carries test copy. */
    src: "/product/project-timeline.png",
    alt: "Project Timeline — stages on a Gantt chart with their progress and tasks",
    spec: "",
    width: 1200,
    height: 900,
  },
  projectsOverview: {
    src: "/product/app/projects-hero.webp",
    alt: "Project Board view: a launch laid out in stages, with the tasks under each",
    spec: "",
    width: 2160,
    height: 1350,
  },
  projectTimeline: {
    src: "/product/app/timeline-hero.webp",
    alt: "Project Timeline: stages on a Gantt chart with their progress, and the detail of one stage below",
    spec: "",
    width: 2160,
    height: 1350,
  },
  projectBoard: {
    src: "/product/app/projects-hero.webp",
    alt: "Project Board: tasks as cards in a column per stage",
    spec: "",
    width: 2160,
    height: 1350,
  },
  timesheet: {
    src: "/product/timesheet.png",
    alt: "Timesheet — activity logged against projects on a weekly calendar",
    focus: { x: 11, y: 43.7, w: 23, h: 37, label: "Logged to a project" },
    spec: "",
    width: 1448,
    height: 850,
  },
  timesheetWeek: {
    /* Monday to Thursday only — the empty back half of the week was most of
       the frame in the half-width slots. */
    src: "/product/timesheet-week.png",
    alt: "Timesheet — activities typed, logged to a project code, with expenses attached",
    focus: { x: 18.8, y: 44.2, w: 39.3, h: 37.4, label: "Logged to a project" },
    spec: "",
    width: 847,
    height: 840,
  },
  reports: {
    src: "/product/reports.png",
    alt: "Reports — logged time by activity type, project, expense and hours, ready to export",
    focus: { x: 64, y: 23.2, w: 31, h: 5.8, label: "Detailed or weekly" },
    spec: "",
    width: 1448,
    height: 800,
  },

  /* -------------------------------------------------------------- sensory */
  tasteTests: {
    src: "/product/taste-tests.png",
    alt: "Taste Tests — publishing a panel report, filtered by product version and taster",
    focus: {
      x: 51.7,
      y: 27.3,
      w: 44.3,
      h: 51.3,
      label: "Filter by product & taster",
    },
    spec: "",
    width: 840,
    height: 800,
  },

  /* ------------------------------------------------------------------ crm */
  crBuilder: {
    src: "/product/cr-builder.png",
    alt: "Customer Requirements Builder — sections, question types and the configure panel",
    focus: { x: 30, y: 40.5, w: 41, h: 24.6, label: "Nested sub-level" },
    spec: "",
    width: 1440,
    height: 932,
  },
  crmPipeline: {
    src: "/product/app/crm-pipeline.webp",
    alt: "Reports, Opportunity Pipeline: each opportunity with its owner, customer, stage and probability",
    spec: "",
    width: 1760,
    height: 1283,
  },

  /* ------------------------------------------------------------- ideation */
  inspire: {
    alt: "Inspire — the ingredient, concept and trend feed",
    spec: `The Inspire feed with trend tiles and a concept being clipped into a brief. ${SHOT}`,
    width: 1600,
    height: 1000,
  },

  /* --------------------------------------------------------------- ai */
  aiAgent: {
    src: "/product/ai-agent-compare.png",
    alt: "AI Agent comparing two recipes side by side, with its sources cited",
    focus: {
      x: 47.6,
      y: 36,
      w: 50.6,
      h: 32,
      label: "Side-by-side comparison",
    },
    spec: "",
    width: 769,
    height: 960,
  },

  /* --------------------------------------------------------- integrations */
  apiDocs: {
    src: "/product/app/rest-api.webp",
    alt: "Admin settings, API section: the public and private keys, masked",
    spec: "",
    width: 1760,
    height: 1283,
  },
  publishExport: {
    src: "/product/publish-recipe.png",
    alt: "Publish Recipe — content, quantities, style, region, method and file type, with the panel previewing live",
    focus: {
      x: 4.4,
      y: 26.9,
      w: 21.3,
      h: 46,
      label: "Content · quantities · style",
    },
    spec: "",
    width: 948,
    height: 840,
  },

  /* ---------------------------------------------------------------- admin */
  adminUsers: {
    src: "/product/app/users-roles.webp",
    alt: "Admin, Users and Groups: every user with their last login, type and status (e-mail addresses blurred)",
    spec: "",
    width: 1760,
    height: 1283,
  },

  /* ------------------------------------------------ app screens, synced
     Exported from the Figma section "04 Pillars — synced to dev"
     (40000475:89173), whose frames were rebuilt from app.dev.flavorstudio.com.
     The frames marked "NOT IN DEV" there were left out on purpose. E-mail
     addresses (users, tasters) are blurred. The four CRM screens come from
     copies in the section "CRM screens — clean sample data (website)"
     (40000586:89111), where the dev test data ("blah blah", staff names,
     real brands, a phone number) was replaced with neutral sample data. */
  projectFiles: {
    src: "/product/app/project-files.webp",
    alt: "A project's Repository tab: images, documents and Inspire collections stored with the project",
    spec: "",
    width: 1760,
    height: 667,
  },
  projectMessages: {
    src: "/product/app/project-messages.webp",
    alt: "A project's Conversations tab: threads per stage and task, with messages and attachments",
    spec: "",
    width: 1760,
    height: 1283,
  },
  projectCardRecipe: {
    src: "/product/app/card-recipe.webp",
    alt: "A task opened from the project timeline, with its stage, dates, creator and assignee",
    spec: "",
    width: 1760,
    height: 1283,
  },
  ingredientGroups: {
    src: "/product/app/ingredient-groups.webp",
    alt: "The formulation grid with supplier columns, costs and the Yield sidebar",
    spec: "",
    width: 1760,
    height: 1283,
  },
  formulationMethod: {
    src: "/product/app/formulation-method.webp",
    alt: "Admin, Recipes, Formulation Options: the formulation method, units, sorting and decimal places",
    focus: { x: 27, y: 24, w: 16, h: 19, label: "Formulation method" },
    spec: "",
    width: 1760,
    height: 1283,
  },
  formulationUnits: {
    src: "/product/app/formulation-method.webp",
    alt: "Admin, Recipes, Formulation Options: units, sorting and decimal places",
    focus: { x: 43, y: 24, w: 38, h: 24, label: "Units & decimals" },
    spec: "",
    width: 1760,
    height: 1283,
  },
  tasteSurvey: {
    src: "/product/app/survey-builder.webp",
    alt: "A taste test's Questionnaire tab: screener, product and follow-up questions",
    spec: "",
    width: 1760,
    height: 847,
  },
  tasteRespondents: {
    src: "/product/app/respondents.webp",
    alt: "A taste test's Tasters tab: each taster with their status (e-mail addresses blurred)",
    spec: "",
    width: 1760,
    height: 590,
  },
  tasteResults: {
    src: "/product/app/data-analysis.webp",
    alt: "A taste test's Results tab: the product version's score as a bar",
    spec: "",
    width: 1760,
    height: 590,
  },
  crmCustomer: {
    src: "/product/app/crm-hero.webp",
    alt: "CRM customer record: customer information beside the history of changes and attachments",
    spec: "",
    width: 2160,
    height: 1350,
  },
  crmOpportunity: {
    src: "/product/app/opportunity-project.webp",
    alt: "CRM opportunity linked to a development project, with its sample requests",
    spec: "",
    width: 1760,
    height: 1283,
  },
  crmSamples: {
    src: "/product/app/sample-request.webp",
    alt: "Reports, Sample Request: each request with customer, requester, product, quantity and delivery date",
    spec: "",
    width: 1760,
    height: 1283,
  },
  integrationEvents: {
    src: "/product/app/integrations-hero.webp",
    alt: "Admin, Integrations, Plex: the events Flavor Studio sends to Plex",
    spec: "",
    width: 2160,
    height: 702,
  },
  webhooks: {
    src: "/product/app/webhooks.webp",
    alt: "Admin, Webhooks: each webhook URL with its error rate and status",
    spec: "",
    width: 1760,
    height: 590,
  },
  erpPlex: {
    src: "/product/app/erp-plex.webp",
    alt: "Admin, Integrations, Plex: the log of recipe conversions sent to production",
    spec: "",
    width: 1760,
    height: 872,
  },

  projectBoardStages: {
    src: "/product/app/projects-hero.webp",
    alt: "Project Board: the tasks of two stages as cards, each with its owner",
    focus: { x: 6, y: 23, w: 50, h: 76, label: "Cards by stage" },
    spec: "",
    width: 2160,
    height: 1350,
  },
  recipeSubLevels: {
    src: "/product/recipe-view.png",
    alt: "The Recipe page with two sub-recipes nested in the formulation grid",
    focus: { x: 5, y: 60, w: 66, h: 24, label: "Sub-recipes" },
    spec: "",
    width: 1440,
    height: 606,
  },
  /* ---------------------------------------- frames from the home walkthroughs */
  reportsDetailed: {
    src: "/stories/reports/detailed.webp",
    alt: "Reports, Detailed: time entries filtered by activity type, project, description, expenses and hours",
    spec: "",
    width: 1440,
    height: 928,
  },
  reportsWeekly: {
    src: "/stories/reports/weekly.webp",
    alt: "Reports, Weekly: hours per activity type across the week, with the same filters",
    spec: "",
    width: 1440,
    height: 928,
  },
  designerInspector: {
    src: "/stories/designer/recipe-name.webp",
    alt: "Publish Designer with an element selected: position, typography, layout and box style in the inspector",
    focus: { x: 83, y: 5, w: 16, h: 90, label: "Inspector" },
    spec: "",
    width: 1440,
    height: 820,
  },
  designerTemplates: {
    src: "/stories/designer/templates.webp",
    alt: "Publish Designer's template menu, listing the templates saved for the recipe",
    spec: "",
    width: 1440,
    height: 820,
  },
  labelStatement: {
    src: "/stories/publishing/pub-statement.webp",
    alt: "Publish Recipe: the ingredient statement generated automatically, with its case and style options",
    spec: "",
    width: 1440,
    height: 941,
  },
} satisfies Record<string, AssetSpec>;

export type ProductAssetKey = keyof typeof productAssets;
