/*
 * Real product assets, in one place.
 *
 * The client's strongest objection to the first design round was that the site
 * showed hand-built HTML approximations of Flavor Studio instead of the product
 * itself — and that the simplified label markup did not follow the official
 * formatting rules those panels are held to.
 *
 * These are now real: every entry below with a `src` is exported straight from
 * the Flavor Studio application design file (Figma "Flavor Studio Application"),
 * including the Nutrition Facts panel, which comes from the label engine's own
 * output rather than being redrawn in HTML.
 *
 * A handful of modules have no design coverage in that file yet — Projects
 * (Timeline/Board), the CRM pipeline and the API reference. Those keep a `spec`
 * and no `src`, so AssetFrame renders a marked placeholder naming exactly what
 * is still needed. Drop the file into /public, add the `src`, and the
 * placeholder becomes the real thing.
 */

export type AssetSpec = {
  /** Path under /public. Absent = still outstanding, renders as a placeholder. */
  src?: string;
  /** What the asset shows. Doubles as the alt text. */
  alt: string;
  /** What we still need from the client, stated concretely. Placeholders only. */
  spec: string;
  width: number;
  height: number;
  kind?: "screenshot" | "label";
};

const SHOT =
  "PNG or JPG, at least 1600px wide, light UI theme, no personal data.";

export const productAssets = {
  /* -------------------------------------------------------------- recipes */
  recipeGrid: {
    src: "/product/recipe-view.png",
    alt: "The Recipe page — formulation grid with the live Yield / Cost sidebar",
    spec: "",
    width: 1440,
    height: 1060,
  },
  recipeVersions: {
    /* Cropped from the Recipe page rather than reusing the whole window: at
       half-column width a 1440px screenshot reduces the interface to texture,
       and the catalogue was showing the identical image for two modules. */
    src: "/product/recipe-versions.png",
    alt: "Recipe versions — V1, Testing and Final switched from the recipe header",
    spec: "",
    width: 963,
    height: 392,
  },
  ingredientLibrary: {
    src: "/product/new-ingredient.png",
    alt: "New Ingredient — basic information, with a separate Canadian label and French ingredient statement",
    spec: "",
    width: 1440,
    height: 900,
  },
  ingredientNutrients: {
    src: "/product/ingredient-nutrients.png",
    alt: "Ingredient nutrients and allergens",
    spec: "",
    width: 1440,
    height: 1362,
  },

  /* ------------------------------------------------------------- labeling */
  nutritionLabelUs: {
    src: "/labels/nutrition-facts-fda.png",
    alt: "FDA Nutrition Facts panel generated by Flavor Studio",
    spec: "",
    width: 688,
    height: 750,
    kind: "label" as const,
  },
  nutritionLabelFormats: {
    /* The layout picker beside the panel it generates, cropped so both are
       actually readable. The full dialog is `publishExport`. */
    src: "/product/label-layouts.png",
    alt: "Label layouts — vertical, tabular, side-by-side, linear, dual column and aggregate — beside the generated panel",
    spec: "",
    width: 677,
    height: 535,
    kind: "label" as const,
  },
  nutrientClaims: {
    src: "/product/nutrient-content-claims.png",
    alt: "Nutrient Content Claims checked against the formula",
    spec: "",
    width: 1440,
    height: 941,
  },
  labelDesigner: {
    src: "/product/publish-designer.png",
    alt: "Publish Designer — template canvas, element palette and the design inspector",
    spec: "",
    width: 1440,
    height: 820,
  },

  /* --------------------------------------------------------------- costing */
  costAssumptions: {
    src: "/product/cost-assumptions.png",
    alt: "Cost sidebar and the shared cost assumptions behind it",
    spec: "",
    width: 1440,
    height: 1131,
  },

  /* ------------------------------------------------------------- projects */
  projectTimeline: {
    alt: "Project Timeline — Gantt view of a launch",
    spec: `Timeline with stage gates, dependencies and dates across a real-looking launch. ${SHOT}`,
    width: 1600,
    height: 1000,
  },
  projectsOverview: {
    alt: "Projects — a launch and its stage gates",
    spec: `A project with its brief, stage gates and the recipes attached to it. ${SHOT}`,
    width: 1600,
    height: 1000,
  },
  projectBoard: {
    alt: "Project Board — tasks by stage",
    spec: `Board view with columns per stage and cards linked to recipes. ${SHOT}`,
    width: 1600,
    height: 1000,
  },
  timesheet: {
    src: "/product/timesheet.png",
    alt: "Timesheet — activity logged against projects on a weekly calendar",
    spec: "",
    width: 1448,
    height: 953,
  },
  reports: {
    src: "/product/reports.png",
    alt: "Reports — logged time by activity type, project, expense and hours, ready to export",
    spec: "",
    width: 1448,
    height: 929,
  },

  /* -------------------------------------------------------------- sensory */
  tasteTests: {
    src: "/product/taste-tests.png",
    alt: "Taste Tests — filtering panels and results",
    spec: "",
    width: 1432,
    height: 873,
  },

  /* ------------------------------------------------------------------ crm */
  crBuilder: {
    src: "/product/cr-builder.png",
    alt: "Customer Requirements Builder — sections, question types and the configure panel",
    spec: "",
    width: 1440,
    height: 1349,
  },
  crmPipeline: {
    alt: "CRM — opportunity pipeline and sample requests",
    spec: `Pipeline view plus a sample request tied to a recipe, with shipment status. ${SHOT}`,
    width: 1600,
    height: 1000,
  },

  /* ------------------------------------------------------------- ideation */
  inspire: {
    alt: "Inspire — the ingredient, concept and trend feed",
    spec: `The Inspire feed with trend tiles and a concept being clipped into a brief. ${SHOT}`,
    width: 1600,
    height: 1000,
  },

  /* --------------------------------------------------------------- ai */
  aiAgent: {
    src: "/product/ai-agent-compare.png",
    alt: "AI Agent comparing two recipes side by side, with its sources cited",
    spec: "",
    width: 1440,
    height: 960,
  },

  /* --------------------------------------------------------- integrations */
  apiDocs: {
    alt: "API documentation",
    spec: "Either a screenshot of the existing API reference, or the source (OpenAPI/Swagger file, or the current docs export) so the reference can be published properly.",
    width: 1600,
    height: 1000,
  },
  publishExport: {
    src: "/product/publish-recipe.png",
    alt: "Publishing and export options — content, quantities, style, region, method and file type",
    spec: "",
    width: 1440,
    height: 941,
  },
} satisfies Record<string, AssetSpec>;

export type ProductAssetKey = keyof typeof productAssets;
