import { AssetFrame } from "@/components/asset-frame";
import { FormulaRail } from "@/components/home/formula-rail";
import { Icon } from "@/components/icon";
import {
  Block,
  SectionHeading,
  SectionLabel,
} from "@/components/layout-primitives";
import { Reveal, RevealStagger } from "@/components/reveal";
import { productAssets } from "@/lib/assets";
import { routes } from "@/lib/routes";

/*
 * Labeling & compliance.
 *
 * This section used to draw a Nutrition Facts panel in HTML, with a scan line
 * sweeping down it. The client was right to object: a hand-built panel cannot
 * satisfy the official formatting rules the real labels are held to, so showing
 * one here misrepresents the product.
 *
 * Both visuals below are now the real thing, exported from the Flavor Studio
 * application: the panel is the label engine's own output, and the Publish
 * Recipe dialog underneath shows the actual publishing options — content,
 * quantities, style, region, layout and file type — which the client noted a
 * visitor never got to see.
 */

const FORMATS = [
  { text: "FDA 2016 format", cls: "bg-blue-200 text-blue-700" },
  { text: "Canadian bilingual", cls: "bg-teal-100 text-[#0e8b73]" },
  { text: "Supplement Facts", cls: "bg-violet-100 text-violet-500" },
  { text: "Big-9 allergen rules", cls: "bg-amber-100 text-[#a97d17]" },
  { text: "Nutrient content claims", cls: "bg-gray-100 text-slate-700" },
];

const LAYOUTS = [
  "Vertical, tabular, side-by-side, linear and dual column",
  "Vitamins and minerals beyond the mandatory four",
  "Ingredient statements and allergen declarations",
  "PNG for internal drafts, high-res vector PDF for packaging",
];

export function Labels() {
  return (
    <Block
      id="labels"
      className="bg-white px-[clamp(28px,3.6vw,64px)] py-[clamp(60px,7vw,100px)]"
    >
      <div className="mx-auto grid max-w-[1180px] grid-cols-[repeat(auto-fit,minmax(min(100%,420px),1fr))] items-center gap-[clamp(40px,5vw,72px)]">
        <Reveal className="flex flex-col items-center">
          <AssetFrame
            {...productAssets.nutritionLabelUs}
            caption="Generated by Flavor Studio's label engine — the same output that goes to your packaging designer."
            className="w-[min(340px,100%)]"
            sizes="340px"
          />
          <FormulaRail
            tone="light"
            className="mt-7 w-full max-w-[420px]"
            caption="The formula the panel above was generated from. Change a percentage and the panel follows."
          />
        </Reveal>

        <div>
          <SectionLabel>Labeling &amp; compliance</SectionLabel>
          <SectionHeading>
            Compliant labels, generated in seconds.
          </SectionHeading>
          <Reveal
            as="p"
            delay={0.12}
            className="mt-[18px] max-w-[52ch] text-[16px] leading-[1.65] text-slate-500"
          >
            The moment your formula changes, the label follows. Nutrition
            recalculates from the ingredient data, yield and serving size — and
            the panel regenerates in the format your market requires,
            print-ready and to spec.
          </Reveal>

          <RevealStagger
            stagger={0.06}
            delay={0.16}
            className="mt-6 flex flex-wrap gap-[10px]"
          >
            {FORMATS.map((chip) => (
              <span
                key={chip.text}
                className={`inline-flex items-center gap-[7px] rounded-full px-[15px] py-2 text-[13px] font-bold ${chip.cls}`}
              >
                <Icon name="check-one" className="text-[14px]" />
                {chip.text}
              </span>
            ))}
          </RevealStagger>

          <RevealStagger
            stagger={0.06}
            delay={0.2}
            className="mt-6 flex flex-col gap-[10px]"
          >
            {LAYOUTS.map((item) => (
              <div
                key={item}
                className="flex items-start gap-[10px] text-[14px] leading-[1.55] text-slate-700"
              >
                <Icon
                  name="check-one"
                  className="mt-[3px] flex-none text-[15px] text-[#0e8b73]"
                />
                {item}
              </div>
            ))}
          </RevealStagger>

          <Reveal delay={0.26} className="mt-[22px]">
            <a
              href={`${routes.features}#labeling`}
              className="inline-flex items-center gap-2 text-[14px] font-extrabold text-blue-600 hover:text-blue-700"
            >
              <span>See every label format and export option</span>
              <Icon name="arrow-right" className="text-[15px]" />
            </a>
          </Reveal>
        </div>
      </div>

      {/* The publish options themselves — the client asked that a visitor be
          able to see what they actually get, not just be told about it. */}
      <div className="mx-auto mt-[clamp(44px,5vw,72px)] max-w-[1180px]">
        <Reveal
          as="h3"
          className="font-display text-center text-[clamp(21px,2.3vw,28px)] leading-[1.2] font-extrabold tracking-[-0.02em] text-slate-800"
        >
          And you choose exactly what gets published.
        </Reveal>
        <Reveal
          as="p"
          delay={0.08}
          className="mx-auto mt-[10px] max-w-[62ch] text-center text-[16px] leading-[1.65] text-slate-500"
        >
          Recipe, label, composition or nutrient content claims. Per serving or
          per 100&nbsp;g. Nutrition Panel or Supplement Facts. Six layouts, the
          region&rsquo;s own rules, and the file type the recipient needs.
        </Reveal>
        <Reveal delay={0.12} className="mt-[clamp(22px,2.8vw,34px)]">
          <AssetFrame
            {...productAssets.publishExport}
            caption="Publish Recipe in Flavor Studio, with the generated panel previewing live as the options change."
            sizes="(max-width: 1180px) 100vw, 1180px"
          />
        </Reveal>
      </div>
    </Block>
  );
}
